openapi: 3.0.3
info:
  title: Todo Service API
  version: 1.0.0
servers:
  - url: http://localhost:8082
paths:
  /todos:
    get:
      summary: Get all todo items
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TodoItemDTO'
      operationId: getAll
    post:
      summary: Add a new todo item
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewTodoItemDTO'
      responses:
        '201':
          description: Todo item created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoItemDTO'
      operationId: createTodo

components:
  schemas:
    TodoItemDTO:
      type: object
      properties:
        id:
          type: string
        description:
          type: string
        status:
          type: string
          enum: ["not done", "done", "past due"]
        createdAt:
          type: string
          format: date-time
        dueDateTime:
          type: string
          format: date-time
        completedAt:
          type: string
          format: date-time
      required:
        - id
        - description
        - status
        - createdAt
        - dueDateTime

    NewTodoItemDTO:
      type: object
      properties:
        description:
          type: string
        dueDateTime:
          type: string
          format: date-time
      required:
        - description
        - dueDateTime

    UpdateTodoItemDTO:
      type: object
      properties:
        description:
          type: string
      required:
        - description